REQUESTS_CPU: 250m
REQUESTS_MEMORY: 1Gi
LIMITS_CPU: 500m
LIMITS_MEMORY: 1Gi
JAVA_OPTS: "-Xms512m -Xmx512m"

KAFKA_TOPIC: email_notifications
KAFKA_DLQ_ENABLED: true
KAFKA_DLQ_TOPIC: email_dlq
KAFKA_BOOTSTRAP_SERVERS: "broker1:29092,broker2:29092"