server:
  port: 9998

serviceUrls:
  subscription: ${SUBSCRIPTION_SERVICE_URL}

spring:
  cloud:
    gateway:
      routes:
        - id: subscription
          uri: ${serviceUrls.subscription}
          predicates:
            - Path=/subscriptions/**
          filters:
            - RewritePath=/subscriptions/documentation/(?<path>.*), /documentation/$\{path}